### ISSUE TITLE
Hi, man :) I've noticed you forgot to delete your private key from the code. 

### ISSUE THREAD

**Issue by mlastovski** [longdh210/ChainBridgeUI#1]
It was interesting for me to steal some funds for experience. I've made a transaction on your behalf on goerli testnet, but no worries, I've returned all the test ETH to your wallet :) Do not forget to remove such sensitive data from github in the future

**Comment by longdh210** [comment]
Hi. thank you for your notice, because I want my friend test my application
but he doesn't know anything about blockchain so I leave my private key in
my repository. I will remove it, thank you very much :D

Vào Th 4, 2 thg 11, 2022 vào lúc 03:56 Mark Lastovskyi <
***@***.***> đã viết:
